### ISSUE TITLE
it Stops Working in 2023.1 and here's the reason i found

### ISSUE THREAD

**Issue by minetyp2232** [kleiders3010/MCreator-1.16.5-Forge-Generator#10]
i have found a bug when updating from 2022.3 to 2023.1: after the update the Workspace just stops working and keeps giving me errors, first i thought my workspace got curopted bcuz of the update but then i found out that when i updated my workspace, the folder "itemgroup" in the location "C:\Users\username\MCreatorWorkspaces\mod_folder\src\main\java\mod_id" got removed and Mcreator can't build without it because it's the folder that keeps the code for the Mod Items Tab, and every item and block needs the items tab in the game so it just gives an error, i tried re-adding the folder and the code but it just gets deleted for some reason, there might be other codes that misteriously gets deleted, cuz in the Console structures also gave an error, i hope this gets fixed soon!

**Comment by kleiders3010** [comment]
This generator is not at all compatible with 2023.1; You need to use 2022.3. There is plenty of other reasons why this won't work right on 2023.1+
