### ISSUE TITLE
No-longer supports: (is biome at: x, y, x tagged in biome tags at "tag")

### ISSUE THREAD

**Issue by mcwoodcraft** [kleiders3010/MCreator-1.16.5-Forge-Generator#2]
MCreator: 2022.3
Plugin: V1.3.0
Windows 10
CPU: AMD
![image](https://user-images.githubusercontent.com/94686352/201399189-b0451171-10c1-4609-85a5-c126af5f44fa.png)
![image](https://user-images.githubusercontent.com/94686352/201399226-9d5f7afe-b1b2-450a-8b3d-1f378854dd09.png)

**Comment by kleiders3010** [comment]
Intentional, biome tags do not exist on 1.16

**Comment by mcwoodcraft** [comment]
Oh really, What replaces them?

**Comment by kleiders3010** [comment]
It used to be biome dictionary, but it got removed from base mcreator, so there is nothing I can do about that

**Comment by mcwoodcraft** [comment]
I see, it's just strange that the block appears to still work on 1.18.2 but I guess that's just how it is.

**Comment by kleiders3010** [comment]
As I said, the block doesn't work on 1.16.5, but works on 1.18.2 and 1.19.2
