### ISSUE TITLE
Liquid tags are required and not optional?

### ISSUE THREAD

**Issue by mcwoodcraft** [kleiders3010/MCreator-1.16.5-Forge-Generator#3]
I'm not 100% sure but whenever I look up the specific issue this pops up:
https://forums.minecraftforge.net/topic/99447-missing-required-tags-1165/

Basically my custom water is acting up causing it to fail to load worlds or create new ones.

This is the log:
https://pastebin.com/fVnuZD2e

**Comment by mcwoodcraft** [comment]
Did have some issues even importing it/using it in procedures as well
```
F:\Workspace\mymod\src\main\java\com\wood\mymod\procedures\TestingProcedure.java:151: error: cannot find symbol 
               ItemStack _setstack = new ItemStack(TestingWaterBlock.bucket); 
                                                   ^
```

**Comment by kleiders3010** [comment]
Can you show what you are trying to do exactly?

**Comment by mcwoodcraft** [comment]
I'll see if I can setup an example workspace

**Comment by kleiders3010** [comment]
Found and fixed the bug, releasing in 1.3.2 in 5-10 minutes. Here is the version for you to try now if you want:
[MCreator 1.16.5 Generator Plugin v1.3.2.zip](https://github.com/kleiders3010/MCreator-1.16.5-Forge-Generator/files/9995487/MCreator.1.16.5.Generator.Plugin.v1.3.2.zip)
Thank you for your report!

**Comment by mcwoodcraft** [comment]
Perfect! Thanks for the quick response!

**Comment by mcwoodcraft** [comment]
Yep it seems to work! Thank you so much!
