### ISSUE TITLE
Entities AI broken

### ISSUE THREAD

**Issue by tiltproof69** [kleiders3010/MCreator-1.16.5-Forge-Generator#4]
Hello! Every entity that is set up, no matter what AI does it have, it just doesn't do anything in game. Just stands there. 
They can be hit and can make sounds, can be killed, but they just stand still (they don't move, they don't attack you, even though they should, cuz thats how i have it set up - to aggro the player). Could you please look into that? Thanks ^^

**Comment by kleiders3010** [comment]
What version of the plugin are you using? And are you in 2022.3?

**Comment by tiltproof69** [comment]
Oh right, sorry. I've tested it both on 1.2.0 and 1.3.2 and the error is on each of them. And yea, I'm using 2022.3.46416 (the latest full release)

**Comment by kleiders3010** [comment]
Can you send your workspace and a screenshot of your plugins folder? Thanks!

**Comment by tiltproof69** [comment]
I've found where is the problem. The problem is [Nerdy's Geckolib plugin](https://mcreator.net/plugin/91484/nerdys-geckolib-plugin-forge-1182-1192), i have version 2.7 of it. I tested it with and without the plugin, and when i took it out, the problem disappeared. However Gecko plugin works with 1.18.2 and 1.19.2 which are supported by Pylo, so something must be off in your plugin, OR in his plugin, but just for 1.16.5. If you dont find anything off in yours, I'll report the issue to Nerdy

Here's my workspace [testobject.zip](https://github.com/kleiders3010/MCreator-1.16.5-Forge-Generator/files/10003687/testobject.zip)

**Comment by kleiders3010** [comment]
You will need to bring this issue to him, since I can't edit his plugins. I will mention it to him today to see what can be done.

**Comment by tiltproof69** [comment]
Thank you

**Comment by kleiders3010** [comment]
He said he would fix it, I will let you know once it's done! You can add me on discord if you want Kleiders#9777

**Comment by tiltproof69** [comment]
Wow that was fast! Thanks! I added you
